// <auto-generated />
using Abgular_API.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Abgular_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Abgular_API.Model.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ny@gmail.com",
                            FullName = "Nayan Raval",
                            Password = "AP48Hjorg5pBxiySvPvGs13CLAofEX+O81o9VXqsljmTLv9BsrGr74AQsPirvVwceg=="
                        },
                        new
                        {
                            Id = 2,
                            Email = "sample@gmail.com",
                            FullName = "Fenal",
                            Password = "AI3AaXZSLFauq7wiWEjtA7qRiK6qvkOLQ3M2Yvhs7rKx/NxnLxHIiw/GkPnI+VVjTQ=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
